# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21c1e39c4804a8c077ca9b148b8766bcc3e1e41af3f566e1c2a46516c2026525b463434a2d46121a3393ec6d8998bd40820ba3206badc1068165993e6232af83

test:
  secret_key_base: 55e693e9b9ab92139a02f542e607ea716c9235cf254a14389b051357e888d169d16c306b69f4b65de475940813df74622be28b6d6665665bf1dfc7802d473943

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
